- // MIR for `match_trunc_i16_i8_failed` before MatchBranchSimplification
+ // MIR for `match_trunc_i16_i8_failed` after MatchBranchSimplification
  
  fn match_trunc_i16_i8_failed(_1: EnumAi16) -> i8 {
      debug i => _1;
      let mut _0: i8;
      let mut _2: i16;
  
      bb0: {
          _2 = discriminant(_1);
          switchInt(move _2) -> [128: bb3, 255: bb4, 0: bb5, 1: bb6, 127: bb7, 65408: bb8, 65535: bb9, 65280: bb10, 65281: bb11, 65407: bb2, otherwise: bb1];
      }
  
      bb1: {
          unreachable;
      }
  
      bb2: {
          _0 = const -127_i8;
          goto -> bb12;
      }
  
      bb3: {
          _0 = const i8::MIN;
          goto -> bb12;
      }
  
      bb4: {
          _0 = const -1_i8;
          goto -> bb12;
      }
  
      bb5: {
          _0 = const 0_i8;
          goto -> bb12;
      }
  
      bb6: {
          _0 = const 1_i8;
          goto -> bb12;
      }
  
      bb7: {
          _0 = const i8::MAX;
          goto -> bb12;
      }
  
      bb8: {
          _0 = const i8::MIN;
          goto -> bb12;
      }
  
      bb9: {
          _0 = const -1_i8;
          goto -> bb12;
      }
  
      bb10: {
          _0 = const 0_i8;
          goto -> bb12;
      }
  
      bb11: {
          _0 = const 1_i8;
          goto -> bb12;
      }
  
      bb12: {
          return;
      }
  }
  
